apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace.name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
    - name: management
      port: {{ .Values.managementPort }}
      targetPort: {{ .Values.managementPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.global.image.repositoryPrefix }}/{{ .Values.image }}:{{ .Values.global.image.tag }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
            - name: management
              containerPort: {{ .Values.managementPort }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          envFrom:
            - configMapRef:
                name: {{ .Values.global.configMapName }}
            {{- if .Values.envSecret }}
            - secretRef:
                name: {{ .Values.global.secretName }}
            {{- end }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.port | quote }}
            - name: MANAGEMENT_PORT
              value: {{ .Values.managementPort | quote }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: management
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: management
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
