spring:
  application:
    name: notification-service
  datasource:
    url: ${NOTIFICATION_DB_URL:jdbc:postgresql://localhost:6435/notification_service}
    username: ${NOTIFICATION_DB_USERNAME:postgres}
    password: ${NOTIFICATION_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: record

app:
  kafka:
    notifications-topic: ${KAFKA_NOTIFICATIONS_TOPIC:bank.notifications}
  notifications:
    scheduler-delay: 5000

management:
  server:
    port: ${MANAGEMENT_PORT:6084}
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
