server:
  port: 6080

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:6060/realms/my-bank}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:6060/realms/my-bank/protocol/openid-connect/certs}

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: account-service
              uri: ${ACCOUNT_SERVICE_URL:http://localhost:6081}
              predicates:
                - Path=/accounts/**
            - id: transfer-service
              uri: ${TRANSFER_SERVICE_URL:http://localhost:6082}
              predicates:
                - Path=/transfers/**
            - id: cash-service
              uri: ${CASH_SERVICE_URL:http://localhost:6083}
              predicates:
                - Path=/cash/**
