apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config/app-config.yaml
  - keycloak/keycloak-realm.yaml
  - keycloak/keycloak.yaml
  - postgres/account-postgres.yaml
  - postgres/transfer-postgres.yaml
  - postgres/cash-postgres.yaml
  - postgres/notification-postgres.yaml
  - kafka/kafka.yaml
  - services/account-service.yaml
  - services/transfer-service.yaml
  - services/cash-service.yaml
  - services/notification-service.yaml
  - services/api-gateway.yaml
  - services/front-ui.yaml
  - ingress/ingress.yaml
