server:
  port: 6085

spring:
  application:
    name: front-ui

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:6088}

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: front-ui
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
        provider:
          keycloak:
            authorization-uri: ${KEYCLOAK_AUTHORIZATION_URI:http://localhost:6060/realms/my-bank/protocol/openid-connect/auth}
            token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:6060/realms/my-bank/protocol/openid-connect/token}
            user-info-uri: ${KEYCLOAK_USER_INFO_URI:http://localhost:6060/realms/my-bank/protocol/openid-connect/userinfo}
            jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:6060/realms/my-bank/protocol/openid-connect/certs}
            user-name-attribute: preferred_username

gateway:
  url: ${GATEWAY_URL:http://localhost:6080}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6071/eureka/
