apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace.name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: postgres
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace.name }}
spec:
  serviceName: {{ .Chart.Name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          args: ["postgres", "-p", "{{ .Values.port }}"]
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.configMapName }}
                  key: {{ .Values.databaseConfigKey }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretName }}
                  key: {{ .Values.usernameSecretKey }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretName }}
                  key: {{ .Values.passwordSecretKey }}
          readinessProbe:
            exec:
              command: ["pg_isready", "-p", "{{ .Values.port }}", "-U", "postgres", "-d", "{{ .Values.databaseName }}"]
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.storage }}
