apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  namespace: {{ .Values.global.namespace.name }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ .Values.global.namespace.name }}
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: {{ .Values.global.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.image }}
          args:
            - start-dev
            - --http-port={{ .Values.port }}
            - --hostname=localhost
            - --hostname-strict=false
            - --import-realm
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretName }}
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretName }}
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KC_HTTP_ENABLED
              value: "true"
          readinessProbe:
            httpGet:
              path: /realms/my-bank
              port: {{ .Values.port }}
            initialDelaySeconds: 40
            periodSeconds: 10
          volumeMounts:
            - name: realm
              mountPath: /opt/keycloak/data/import/realm-export.json
              subPath: realm-export.json
              readOnly: true
      volumes:
        - name: realm
          configMap:
            name: keycloak-realm
