server:
  port: 6088

spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file:../config-repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6071/eureka/
