apiVersion: v1
kind: Service
metadata:
  name: front-ui
  namespace: my-bank
spec:
  selector:
    app: front-ui
  ports:
    - name: http
      port: 6085
      targetPort: 6085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-ui
  namespace: my-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-ui
  template:
    metadata:
      labels:
        app: front-ui
    spec:
      containers:
        - name: front-ui
          image: my-bank/front-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6085
          envFrom:
            - configMapRef:
                name: my-bank-app-config
          env:
            - name: SERVER_PORT
              value: "6085"
          readinessProbe:
            tcpSocket:
              port: 6085
            initialDelaySeconds: 40
            periodSeconds: 10
